apply plugin: "com.liferay.node"

node {
	global = false
	nodeVersion = "18.18.0"
	useNpm = false
	yarnVersion = "1.22.19"
}

def nodeBinDir = "${node.nodeDir}/bin/node"
def yarnBinDir = "${node.nodeDir}/lib/node_modules/yarn/yarn-${node.yarnVersion}.js"

task yarnInstallOsbFaroWeb(type: Exec) {
	executable = file(nodeBinDir)

	args = [file(yarnBinDir), "install"]

	dependsOn downloadNode
	workingDir = projectDir
}

task yarnBuildOsbFaroWeb(type: Exec) {
	executable = file(nodeBinDir)

	args = [file(yarnBinDir), "webpack"]

	dependsOn yarnInstallOsbFaroWeb
	workingDir = projectDir
}

task yarnRunTestOsbFaroWeb(type: Exec) {
	executable = file(nodeBinDir)

	args = [file(yarnBinDir), "test"]

	dependsOn yarnBuildOsbFaroWeb
	workingDir = projectDir
}

tasks.named('packageRunTest') {
	dependsOn yarnRunTestOsbFaroWeb
}
